### PR TITLE
Add support for multiple account holders (pt-BR: Conta conjunta)

### PR DESCRIPTION
**Pull request by ludufre**
This PR add supports to accounts with multiple account holders. Use the `-n, --name` argument.

### CODE REVIEW

**Comment by ludufre** [comment]
Also fixes de button login that have changed.

**Comment by ludufre** [comment]
@viniciusgava please merge this :)

**Comment by viniciusgava** [comment]
Hey @ludufre thank you for the contribution!!

I am traveling right now. Next week I'll merge your PR since I'll need to build the docker image manually in order to publish the release.

**Comment by viniciusgava** [comment]
@ludufre I just published the release and docker images as `1.4.0`. 
Thank you for the contribution!

Release: https://github.com/viniciusgava/itauscraper/releases/tag/1.4.0

**Pull request merged**
